### ISSUE TITLE
CSS Framework

### ISSUE THREAD

**Issue by HoBi** [sunfreitas/owlcss#1]
Hi man,I have the same framework (the same name) and I have saw you have it too. Do you want to join us? We work in Sass, but we also want to do the Less version, so if you want, text me on Gitter - link you can find in https://github.com/oslcss/owlcss or http://owlcss.com

Bye!

**Comment by sunfreitas** [comment]
Thanks!

But I didn't start the project yet. If you would like some help I
appreciate join your team.


On Wed, Apr 1, 2015 at 3:17 AM, Honza Bittner <notifications@github.com>
wrote:

> Hi man,I have the same framework (the same name) and I have saw you have
> it too. Do you want to join us? We work in Sass, but we also want to do the
> Less version, so if you want, text me on Gitter - link you can find in
> https://github.com/oslcss/owlcss or http://owlcss.com
>
> Bye!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sunfreitas/owlcss/issues/1>.
>



-- 
*Tashi Delek!**,*
*Francisco Freitas/ Zamba Chögyal*
*Tecnólogo em Sistemas para Internet*

*"Até que eu alcance a iluminação, tomo refúgio nas trés jóias. Pelo mérito
de realizar as seis perfeições, possa eu alcançar a mente desperta para o
benefício de todos os seres."*

**Comment by hobi** [comment]
Thx for join us on Gitter - do not forget attend regular. :)
